version: '3' # versiom del docker-compose
services:
  web:
    build: . #se contruye la imagen en el directorio actual done esta el dockerfile
    ports: #maopeo de puertos entre el contenedor y el host
      - "5000:5000"
    volumes: #monta los archivos del host en el contenedor
      - .:/app
    environment: # Define las variables de entorno
      - FLASK_ENV=development
    
    mysql:  #servicio de mysql que son de la base de datos qwue se va a usar
      image: mysql:5.2.1
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: events_abc_db
        MYSQL_USER: abc_group
        MYSQL_PASSWORD: 123abc
      ports:
        - "3306:3306"


  